name: Build & Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node (from .nvmrc) + cache npm
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install deps & build
        run: |
          npm ci
          npm run quick-build
        env:
          CI: true

      # helpful once—keep if you’re still unsure
      - name: Show top-level dirs and likely site files
        run: |
          ls -la
          find . -maxdepth 3 -type f -name 'index.html' -print

      # Detect a site directory that contains an index.html
      - name: Determine site directory
        id: site
        shell: bash
        run: |
          # common output dirs to try first
          for d in bundle build dist docs public out; do
            if [ -d "$d" ] && [ -f "$d/index.html" ]; then
              echo "dir=$d" >> "$GITHUB_OUTPUT"
              echo "Detected site dir: $d"
              exit 0
            fi
          done
          # fallback: nearest parent of an index.html (depth<=3)
          CANDIDATE=$(dirname "$(find . -maxdepth 3 -type f -name index.html | head -n1)")
          if [ -n "$CANDIDATE" ] && [ -f "$CANDIDATE/index.html" ]; then
            # trim leading ./ if present
            echo "dir=${CANDIDATE#./}" >> "$GITHUB_OUTPUT"
            echo "Detected site dir (fallback): ${CANDIDATE#./}"
            exit 0
          fi
          echo "No build output with index.html found." >&2
          exit 1

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.site.outputs.dir }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
