name: Build & Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 16 (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install deps & build
        run: |
          npm ci
          npm run quick-build
        env:
          CI: true

      # Your site output folder; adjust if different
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: bundle

      # Offline bundle (optional)
      - name: Package offline bundle
        run: |
          mkdir -p bundle-offline/LingView
          mv bundle bundle-offline/LingView
      - name: Save offline bundle
        uses: actions/upload-artifact@v4
        with:
          name: LingView-local
          path: bundle-offline

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4